#!/bin/bash
# Shows how to get certain dates or add days etc. to a certain date
FRIDAY=$(date '+%C%y-%m-%d' -d "Fri")
echo "This Friday's date is: $FRIDAY"

FOLLOWING_FRIDAY=$(date '+%C%y-%m-%d' -d "$FRIDAY+7days")
echo "Next Friday's date is: $FOLLOWING_FRIDAY"
