#!/bin/bash
echo -n "\"-n\" means no new line at the end."
echo " The next echo continues on same line"

echo
echo -n "This text will be overwritten. Continue? "
read -p "" -n 1
echo -e "\rUsing \"\\\r\" will overwrite the last output"

echo
echo -n "An entire line will not be deleted if it's not long enough. Continue? "
read -p "" -n 1
echo -e "\rSee there's still characters to the right -->  "

echo
echo -en "You can delete an entire line by using a special character. Continue? \r"
read -p "" -n 1
echo -en "\033[2K" # Delete everything on line regardless of cursor position
echo -e "Everything Gone :)"
