#!/bin/bash
Black='\e[0;30m'
DarkGray='\e[1;30m'
Blue='\e[0;34m'
LightBlue='\e[1;34m'
Green='\e[0;32m'
LightGreen='\e[1;32m'
Cyan='\e[0;36m'
LightCyan='\e[1;36m'
Red='\e[0;31m'
LightRed='\e[1;31m'
Purple='\e[0;35m'
LightPurple='\e[1;35m'
Brown='\e[0;33m'
Yellow='\e[1;33m'
LightGray='\e[0;37m'
White='\e[1;37m'
Bold="\e[1m"
Clear='\e[0m'

echo "\"-e\" is required if expressions like colors are used. For example:"
echo -e " - ${Black}Black"
echo -e " - ${DarkGray}DarkGray"
echo -e " - ${Blue}Blue"
echo -e " - ${LightBlue}LightBlue"
echo -e " - ${Green}Green"
echo -e " - ${LightGreen}LightGreen"
echo -e " - ${Cyan}Cyan"
echo -e " - ${LightCyan}LightCyan"
echo -e " - ${Red}Red"
echo -e " - ${LightRed}LightRed"
echo -e " - ${Purple}Purple"
echo -e " - ${LightPurple}LightPurple"
echo -e " - ${Brown}Brown"
echo -e " - ${Yellow}Yellow"
echo -e " - ${LightGray}LightGray"
echo -e " - ${White}White"
echo -e " - ${Clear}${Bold}Bold" # Appears just like ${White}, this code just emphasises the set color
echo -e " - ${Clear}Clear"
echo "The old color continues from the previous line (as shown by the color of the dashes above"
