#!/bin/bash

# # removes characters from the beginning of the string
# % removes characters from the end of the string
# Single character removes smallest matching string
# Double characters removes longest matching string

fullString="This is my full string"
echo "fullString=\"$fullString\""

# Remove all chacaters from the start of the string to the first space character
# i.e. Show all but first word
echo "\${fullString#* }=\"${fullString#* }\""

# Remove all characters from the start of the string to the last space character
# i.e Get last word
echo "\${fullString##* }=\"${fullString##* }\""

# Remove all characters from the end of the string to the first space character (from the end)
# i.e. Get all but last word
echo "\${fullString% *}=\"${fullString% *}\""

# Remove all characters from the end of the line to the last space character (from the end)
# i.e. Get first word
echo "\${fullString%% *}=\"${fullString%% *}\""

# Remove "full" from the string
echo "\${fullString/full}=\"${fullString/full}\""

# Replace "my" with "your"
echo "\${fullString/my/your}=\"${fullString/my/your}\""

# Replaces first space character with colon
echo "\${fullString/ /:/}=\"${fullString/ /:}\""

# Replace ALL space characters with colon
echo "\${fullString// /:/}=\"${fullString// /:}\""
